name: GitHub Pages

on:
  push:
    branches: main

jobs:
  build_pages:
    runs-on: ubuntu-latest

    if: github.actor != 'nektos/act'

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: pnpm
      - run: pnpm install
      - run: pnpm run docs
      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs

  deploy_pages:
    needs: build_pages

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
