name: Node.js Patch

on: workflow_dispatch

jobs:
  patch:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    if: github.actor != 'nektos/act' && github.ref_name == 'main'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          ssh-key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - id: patch
        run: |
          echo "VERSION=$(pnpm version patch --no-git-tag-version)" >> "$GITHUB_OUTPUT"
          git add .

      - id: commit
        uses: qoomon/actions--create-commit@v1
        with:
          message: 🔖 ${{ steps.patch.outputs.VERSION }}

      - name: Push
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "$DEPLOY_KEY_PRIVATE"
          git push
        env:
          DEPLOY_KEY_PRIVATE: ${{ secrets.DEPLOY_KEY_PRIVATE }}

      - run: gh release create "$VERSION" --generate-notes --target "$COMMIT" --title "$VERSION"
        env:
          COMMIT: ${{ steps.commit.outputs.commit }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.patch.outputs.VERSION }}
